version: '2'

services:
  db:
    image: couchdb
    ports:
      - "5984:5984"
    volumes:
      - ./.couchdb:/usr/local/var/lib/couchdb

  web:
    image: dashing
    build: .
    command: bundle exec rackup -s puma -p 3030
    volumes:
      - .:/dashboard
    ports:
      - "3030:3030"
    depends_on:
      - db
