version: '2'

services:
  dbserver:
    image: couchdb
    ports:
      - "5984:5984"
    volumes:
      - ./.couchsummary:/usr/local/var/lib/couchdb

  dbteam:
    image: couchdb
    ports:
      - "5985:5984"
    volumes:
      - ./.couchteam:/usr/local/var/lib/couchdb


  web:
    image: dashing-web
    build: .
    command: bundle exec rackup -s puma -p 8080
    volumes:
      - .:/dashboard
    ports:
      - "80:8080"
    depends_on:
      - dbteam
    environment:
      MODE: team
      TEAM: test
      DBURL: http://dbteam:5984/


  summary:
    image: dashing-summary
    build: .
    command: bundle exec rackup -s puma -p 8080
    volumes:
      - .:/dashboard
    ports:
      - "8080:8080"
    depends_on:
      - dbserver
    environment:
      MODE: summary
      DBURL: http://dbserver:5984/
