version: '2'

services:
  dbserver:
    image: couchdb
    ports:
      - "5984:5984"
    volumes:
      - ./.couchsummary:/usr/local/var/lib/couchdb

  dbteam:
    image: couchdb
    ports:
      - "5985:5984"
    volumes:
      - ./.couchteam:/usr/local/var/lib/couchdb


  web:
    image: dashboard
    build: .
    command: bundle exec rackup -s puma -p 8080
    volumes:
      - .:/dashboard
    ports:
      - "80:8080"
    depends_on:
      - dbteam
    environment:
      MODE: team
      TEAM: test
      SUMMARY_SERVER http://web:8080
      DBURL: http://dbteam:5984/

  summary:
    image: dashboard
    build: .
    command: bundle exec rackup -s puma -p 8080
    volumes:
      - .:/dashboard
    ports:
      - "8080:8080"
    depends_on:
      - dbserver
    environment:
      MODE: summary
      DBURL: http://dbserver:5984/
      
  test_env:
    image: test_env
    build: tests/
    command: bash -c "service xvfb start; export DISPLAY=:10; ruby /dashboard/tests/bvt.rb"
    privileged: true
    depends_on:
      - summary
    volumes:
      - .:/dashboard
    ports:
      - "4444:4444"
      - "9516:9516"
